version: '3'

networks:
  internal:
    external: false

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'ScrapeZone'
    volumes:
      - /app/node_modules
      - ./:/app
    working_dir: /app
    ports: 
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - internal
    security_opt:
      - no-new-privileges:true

  mongo:
    image: mongo:4.2.6
    container_name: 'ScrapeZoneMongoDB'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ${PWD}/scrape-zone.db/data/db:/data/db
    networks:
      - internal